# This file was automatically generated by passthru.fetch-deps.
# Please dont edit it manually, your changes might get overwritten!

{ fetchNuGet }: [
  (fetchNuGet { pname = "Microsoft.DotNet.ILCompiler"; version = "8.0.0-preview.3.23174.8"; sha256 = "0zsh4najx636gv7l4acxvxcx778baczcm45hsfkmjdc7g5cs1k2x"; })
  (fetchNuGet { pname = "Microsoft.NET.ILLink.Tasks"; version = "8.0.0-preview.3.23174.8"; sha256 = "1h86pnwzrlb3yg2328rqmc6sgcwi1dbbyqgh20l58z064sfa12wx"; })
  (fetchNuGet { pname = "runtime.osx-arm64.Microsoft.DotNet.ILCompiler"; version = "8.0.0-preview.3.23174.8"; sha256 = "10p15rxwh14kwfjb57p1imyas4bfm64hwipk169n94cflk3pl7d4"; })
]
