# This file was automatically generated by passthru.fetch-deps.
# Please dont edit it manually, your changes might get overwritten!

{ fetchNuGet }: [
  (fetchNuGet { pname = "Microsoft.DotNet.ILCompiler"; version = "8.0.0-preview.4.23259.5"; sha256 = "178hvmkqamwq2zfifmyj63zwl4fdqwx5wljf84cy5wa4wr0grjj3"; })
  (fetchNuGet { pname = "Microsoft.NET.ILLink.Tasks"; version = "8.0.0-preview.4.23259.5"; sha256 = "1km3l73p8khiywjg02wnfmxgpiznhq53b0vc2l5qhkmb0085jw8m"; })
  (fetchNuGet { pname = "runtime.osx-arm64.Microsoft.DotNet.ILCompiler"; version = "8.0.0-preview.4.23259.5"; sha256 = "1m3983kds7kwx2nllifs4nw31nsgbz8083q1aig41v0j73m52db9"; })
]
